lizards-and-pumpkins/sample-project

README.md
=> Issue #8: Add README

src/lizards-and-pumpkins/src/Util/Factory/DemoProjectFactory.php
=> Issue #16: add missing interface to DemoProjectFactory

composer.json
To use this repo as a repository, we need at least name, so add everything
=> FIXES #19: Add missing composer.json  data

tests/Unit/phpunit.xml.dist
=> Issue #18: Rename unit test suite

composer.json, src/lizards-and-pumpkins/bin/runContentBlockImport.php, src/lizards-and-pumpkins/bin/triggerTemplateUpdate.php, src/lizards-and-pumpkins/pub/css/common.css, src/lizards-and-pumpkins/pub/js/product_listing.js, src/lizards-and-pumpkins/pub/js/search_autosuggestion.js, src/lizards-and-pumpkins/src/Util/Factory/DemoProjectFactory.php, src/lizards-and-pumpkins/theme/template/header.phtml, src/lizards-and-pumpkins/theme/template/list.phtml, tests/Unit/Suites/Util/Factory/DemoProjectFactoryTest.php
=> Issue #25: Update project to catalog version 0.14.1

build/buildLizardsAndPumpkinsSnippets.sh
Remove obsolete template product_search_autosuggestion from call to triggerTemplateUpdate.php
=> Issue #23: Remove obsolete template product_search_autosuggestion

src/lizards-and-pumpkins/theme/template/left.phtml
=> Issue #15: Prevent collapsing of left column if no filters are available

build/init.sh
=> Issue #38: Use relative paths for symlinks

src/magento-themes/magento-sample-theme/app/design/frontend/lizardsandpumpkins/default/template/customer/form/login_register.phtml
=> Issue #40: Add form key to customer registration form template

src/magento-themes/magento-sample-theme/app/design/frontend/lizardsandpumpkins/default/layout/local.xml
Both of those caused the browser to send requests to Magento which where processed as page requests, even though they don't exist.
Closes #45
=> Issue #45: Remove styles.css and print.css references

src/magento-themes/magento-sample-theme/app/design/frontend/lizardsandpumpkins/default/template/customer/form/login_register.phtml
=> Issue #42: Display error messages on login and registration

src/lizards-and-pumpkins/pub/css/common.css, src/lizards-and-pumpkins/pub/js/search_autosuggestion.js
=> Issue #34: Make search suggestions selectable with arrow keys

src/lizards-and-pumpkins/theme/template/header.phtml
=> Issue #35: Make mini cart icon clickable as link to cart page

src/magento-themes/magento-sample-theme/app/design/frontend/lizardsandpumpkins/default/layout/local.xml, src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/css/modules/cart.css
=> Issue #36: Style cart page

src/lizards-and-pumpkins/bin/reportDomainEventProcessingAvg.php
=> Issue #53: Make command strict mode compliant

src/lizards-and-pumpkins/bin/manage-workers.sh, src/lizards-and-pumpkins/bin/shutdownConsumerProcess.php
=> Shutdown PHP worker processes via messages

src/lizards-and-pumpkins/src/Util/Factory/DemoProjectFactory.php, tests/Unit/phpunit.xml.dist
Additional changes in phpunit.xml.dist to make the tests pass again.
Closes #61
=> Delegate quue creation to master factory

src/lizards-and-pumpkins/bin/runContentBlockImport.php, src/lizards-and-pumpkins/bin/runImport.php, src/lizards-and-pumpkins/bin/triggerTemplateUpdate.php
=> Avoid blocking or processing too few messages on one-off queue msgs processing

src/lizards-and-pumpkins/pub/js/filter_navigation.js, src/lizards-and-pumpkins/pub/js/product_listing.js, tests/JavaScript/FilterNavigationSpec.js, tests/JavaScript/SpecRunner.html
=> Issue #57: Support both dot and comma as decimal separator

composer.json, src/lizards-and-pumpkins/src/Util/Factory/DemoProjectFactory.php
=> Issue #71: Set required "catalog" version to 0.15.0-alpha

src/lizards-and-pumpkins/bin/runImport.php, src/lizards-and-pumpkins/bin/triggerTemplateUpdate.php
=> Issue #73: Add new required DataVersion to importing actions

src/lizards-and-pumpkins/pub/js/search_autosuggestion.js, src/magento-themes/magento-sample-theme/app/design/frontend/lizardsandpumpkins/default/template/catalogsearch/form.mini.phtml, src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/css/basic.css, src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/js/modules/header.js
=> Issue #77: Add search autosuggestion to Magento

pub/index-magento.php
Please merge after https://github.com/lizards-and-pumpkins/magento-connector/pull/333
=> Issue #75: Add Autoloader to fix problem

composer.json, src/lizards-and-pumpkins/pub/css/product_listing.css, src/lizards-and-pumpkins/pub/js/filter_navigation.js, tests/JavaScript/FilterNavigationSpec.js, tests/Unit/Suites/Context/Country/DemoProjectCountryContextPartBuilderTest.php, tests/Unit/Suites/Context/DemoProjectContextSourceTest.php, tests/Unit/Suites/Context/Locale/DemoProjectLocaleContextPartBuilderTest.php, tests/Unit/Suites/Context/Website/DemoProjectWebsiteContextPartBuilderTest.php, tests/Unit/Suites/Context/Website/RequestToWebsiteMapTest.php, tests/Unit/Suites/Context/Website/WebsiteToCountryMapTest.php, tests/Unit/Suites/Import/Product/Image/DemoProjectProductImageFileLocatorTest.php, tests/Unit/Suites/Import/Product/View/DemoProjectConfigurableProductViewTest.php, tests/Unit/Suites/Import/Product/View/DemoProjectProductViewLocatorTest.php, tests/Unit/Suites/Import/Product/View/DemoProjectSimpleProductViewTest.php, tests/Unit/Suites/Import/Tax/DemoProjectTaxRateTest.php, tests/Unit/Suites/Import/Tax/DemoProjectTaxServiceLocatorTest.php, tests/Unit/Suites/Import/Tax/DemoProjectTaxableCountriesTest.php, tests/Unit/Suites/ProductDetail/Import/View/DemoProjectProductPageTitleTest.php, tests/Unit/Suites/ProductListing/Import/DemoProjectProductListingTitleSnippetRendererTest.php, tests/Unit/Suites/Util/Factory/DemoProjectFactoryTest.php
=> Issue #85: Bump required "catalog" version to 0.17.0

src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/css/basic.css
=> Issue #98: Add selector for email type input fields

composer.json
=> Issue #110: Update catalog repo dependency to ~2.0.0

composer.json
=> #113: Bump required "catalog" version to 3.1.0

composer.json
=> #115: Loosen catalog dependency requirement to major version only

composer.json
=> #117: Fix PHP version requirement
